"""Add product_category table and category_id to project_cases

Revision ID: 32914cc96883
Revises: 000000000001
Create Date: 2025-11-01 21:33:21.824882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '32914cc96883'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if table_name not in inspector.get_table_names():
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Check if product_categories table exists before creating
    if not table_exists('product_categories'):
        op.create_table('product_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False, comment='類別名稱'),
        sa.Column('slug', sa.String(length=100), nullable=False, comment='URL 友好名稱'),
        sa.Column('description', sa.Text(), nullable=True, comment='描述'),
        sa.Column('status', sa.Boolean(), nullable=False, comment='狀態'),
        sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
        )
    else:
        print("Table 'product_categories' already exists, skipping creation")
    
    # Check if project_cases table exists and add category_id if needed
    if table_exists('project_cases'):
        if not column_exists('project_cases', 'category_id'):
            with op.batch_alter_table('project_cases', schema=None) as batch_op:
                batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True, comment='類別ID'))
            
            # Create foreign key if product_categories table exists
            if table_exists('product_categories'):
                bind = op.get_bind()
                inspector = inspect(bind)
                fk_name = 'fk_project_cases_category_id'
                fks = [fk['name'] for fk in inspector.get_foreign_keys('project_cases')]
                if fk_name not in fks:
                    with op.batch_alter_table('project_cases', schema=None) as batch_op:
                        batch_op.create_foreign_key(fk_name, 'product_categories', ['category_id'], ['id'])
        else:
            print("Column 'category_id' already exists in 'project_cases', skipping")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('project_cases'):
        if column_exists('project_cases', 'category_id'):
            with op.batch_alter_table('project_cases', schema=None) as batch_op:
                bind = op.get_bind()
                inspector = inspect(bind)
                fks = [fk['name'] for fk in inspector.get_foreign_keys('project_cases')]
                if 'fk_project_cases_category_id' in fks:
                    batch_op.drop_constraint('fk_project_cases_category_id', type_='foreignkey')
                batch_op.drop_column('category_id')

    if table_exists('product_categories'):
        op.drop_table('product_categories')
    # ### end Alembic commands ###
