"""Add product_category table and category_id to project_cases

Revision ID: 32914cc96883
Revises: a34c0bbd7656
Create Date: 2025-11-01 21:33:21.824882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32914cc96883'
down_revision = 'a34c0bbd7656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='類別名稱'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL 友好名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='狀態'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('project_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True, comment='類別ID'))
        batch_op.create_foreign_key('fk_project_cases_category_id', 'product_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_cases_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('product_categories')
    # ### end Alembic commands ###
