"""Add image field to product_categories

Revision ID: 4ca104a72590
Revises: 32914cc96883
Create Date: 2025-11-01 22:06:23.387255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4ca104a72590'
down_revision = '32914cc96883'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if table_name not in inspector.get_table_names():
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Check if product_categories table exists and add image column if needed
    if table_exists('product_categories'):
        if not column_exists('product_categories', 'image'):
            with op.batch_alter_table('product_categories', schema=None) as batch_op:
                batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True, comment='類別圖片'))
        else:
            print("Column 'image' already exists in 'product_categories', skipping")
    else:
        print("Table 'product_categories' does not exist, skipping migration")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('product_categories'):
        if column_exists('product_categories', 'image'):
            with op.batch_alter_table('product_categories', schema=None) as batch_op:
                batch_op.drop_column('image')
    # ### end Alembic commands ###
