"""Add image field to product_categories

Revision ID: 4ca104a72590
Revises: 32914cc96883
Create Date: 2025-11-01 22:06:23.387255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca104a72590'
down_revision = '32914cc96883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True, comment='類別圖片'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
