"""Add users table with role

Revision ID: a34c0bbd7656
Revises: 
Create Date: 2025-11-01 14:20:51.523635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34c0bbd7656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用戶名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='電子郵件'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密碼雜湊'),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False, comment='角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最後登入時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
