"""Add image field to contacts

Revision ID: b5c8d9e2f4a1
Revises: 4ca104a72590
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b5c8d9e2f4a1'
down_revision = '4ca104a72590'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if table_name not in inspector.get_table_names():
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Check if contacts table exists before modifying
    if table_exists('contacts'):
        if not column_exists('contacts', 'image'):
            with op.batch_alter_table('contacts', schema=None) as batch_op:
                batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True, comment='圖片'))
        else:
            print("Column 'image' already exists in 'contacts', skipping")
    else:
        print("Table 'contacts' does not exist, skipping migration. Please create contacts table first.")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('contacts'):
        if column_exists('contacts', 'image'):
            with op.batch_alter_table('contacts', schema=None) as batch_op:
                batch_op.drop_column('image')
    # ### end Alembic commands ###

