"""Add page_settings table for page banners

Revision ID: ed9a3a646336
Revises: b5c8d9e2f4a1
Create Date: 2025-11-01 22:57:32.695208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9a3a646336'
down_revision = 'b5c8d9e2f4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False, comment='頁面類型'),
    sa.Column('banner_image', sa.String(length=255), nullable=True, comment='Banner 圖片'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_settings')
    # ### end Alembic commands ###
